---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 8Gi # scale up as needed

